//ベイス
ここではベイズ統計モデリングという手法を使って投票データの傾向の説明を試みた結果(顛末)を書きます。

==== ベイズ統計について

パラメーター

stanという言語記述します。

==== 言語とツール

ここではpythonのライブラリpystanを用いて
可視化にはarvizというライブラリを使います。

==== モデリングと結果

このように
は階層モデルと呼ばれます。
今回のキャラとそれが登場した整数作品のような階層的な関係が実際にある場合
データの分布の観点からは　過分散と呼ばれる問題に対処できると

別のモデルとして投票期間によらない作品の影響力を加えたモデル

===== キャラ

- 和モデル

stem:[
 normVote_{i,t} \sim Dir(\sum_{l=1}^{TM} main_{j(i,t-l),t-l} \sigma_{j,l} \\ + \sum_{l=1}^{TM} boss_{j(i,t-1),t-l}Lv_i b_{j(i,t-l),l} 
 +\sum_{l=1}^{TM} sub_{j(i,t-l)} s_{j,l}+\epsilon_i
 )
]

- 積和モデル

stem:[
 normVote_{i,t} \sim Dir( (\sum_{l=1}^{TM} main_{j(i,t-l),t-l} \sigma_{j,l} \\ + \sum_{l=1}^{TM} boss_{j(i,t-1),t-l}Lv_i b_{j(i,t-l),l} 
 +\sum_{l=1}^{TM} sub_{j(i,t-l)} s_{j,l})*\epsilon_i
 )
]

//hyper dth[i]=sum(mains)+sum(bosses)+sum(subs)+hifuu+book+misc+indivisual[i];
//sumnidivisual dth[i]=(sum(mains)+sum(bosses)+titlebase+sum(subs) +noninttitlebase +sum(hifuu)+sum(book)+sum(misc))+indivisual[i];

===== 音楽

キャラと同様に和モデル、積和モデルを

計算上の特性である属性に含まれるかどうかというflagをdataframeとして持っておく方が計算が高速化することがわかりました。

- 積和モデル
収束しました。

===== 事前分布

パラメーターにデータによる
stanでは事前分布を指定しない場合は一様分布が用いられます。
「StanとRでベイズ統計モデリング」にも書かれており、

逆ガンマ分布あるいは半コーシー分布という裾の広い分布関数を使用すると良いとされています。
stanでは

===== 発展的話題

- 因果推論

- 情報量基準

- 他のデータの利用
