include::styles.adoc[]

= 東方Project人気投票の解析　〜可視化＆ベイズ統計モデリング〜

== はじめに

過去20年以上にわたる東方Projectの楽曲、キャラ(人妖)の人気投票データは年を経るごとに膨大になり、情報が蓄積されています。その中から目で見てわかるパターンの抽出とそれを説明する数理モデルの提唱と解析を行いました。

人気投票サイト https://toho-vote.info/result のデータと東方Wiki http://thwiki.info 東方元ネタWiki 2nd((https://seesaawiki.jp/toho-motoneta_2nd/)) の作品、楽曲、キャラ情報を使用し、解析コードとそれによって整形されたデータは
https://github.com/xiangze/toubou_vote_analysis/data においてあります。pandas,pystanなどpythonのライブラリを用いており、Googleのcolaboratoryを用いて実行できます。また本書の原稿もbook以下に置いてあります。

NOTE: 本投票において公開されたデータは、統計や考察などの目的であれば、自己の責任に基づき自由に使用しても構いませんとのことです

本書の内容の一部はブログ記事

- https://xiangze.hatenablog.com/entry/2022/12/21/210352
- https://xiangze.hatenablog.com/entry/2023/01/01/232744

に基づいたものです。

== 東方Projectのすごいざっくりした紹介

「東方コミュニティ白書2016」および上記ブログにて詳しく書かれておりここでは概略を述べます。
東方Projectは上海アリス幻樂団によるシューティングゲームで25年以上に渡る歴史を持っています。 最近ではスマホゲームのタイトルも複数リリースされ、多くの二次創作があること、音楽の人気が高いことでも知られています。

東方Project作品は以下のように分類されます。

- 旧作 1996~1998年にPC98用に作られたゲーム作品で現在は入手困難だが 音楽には現在でも人気なものがある。わずかなキャラクターが以後の整数作品と重複する
- 整数作品 上海アリス幻樂団により2002年の東方紅魔郷以降に作られたWindows向けシューティングゲーム、Steamで入手できる作品もある。毎作品ステージごとのボスが新キャラとして登場し、対応する新曲があるのが通例。プレーアブルキャラクターは自機と呼ばれることが多い。
- 非整数作品 黄昏フロンティアと上海アリス幻樂団が製作した対戦格闘ゲーム、アクションゲームで準公式として扱われる。既存の整数作品のキャラクターの再登場が多いが、新キャラが登場することもある。
- 音楽CD ZUN氏作曲のものでもともと東方紅魔郷が音楽CDとして発表されるはずだった説もあるくらい音楽に力を入れている。整数、非整数作品登場曲の再録、アレンジとオリジナル曲がある。
- 書籍「東方鈴奈庵」などの書籍、漫画作品の主人公が新キャラの場合が多い

選択式でキャラクター(人妖)、音楽、作品に対してそれぞれ7,10,5票入れることができ特に推しには2票入れられます。その傾向からキャラクターのよりコアな人気、投票者がキャラクターについてどれくらい知っているか、コミュニティーの流動性まで知ることができ興味深いですが本書で扱う範囲を超えています。
NOTE:東方カンファレンスで考察がされています。 https://twitter.com/blue_comment/status/1644603082469429249

== データの準備

人気投票サイトから各回の投票結果htmlをダウンロードします。17回からは動的にサイトが生成されるようになりましたがseleniumを使うと自動でダウンロードができます。

まず文字コードの変遷が時代を感じさせます。

.文字コード
|===
|投票回	|文字コード

|1	
|CP932

|2~4
|	Shift_JIS

|5~10
|	EUC-JP

|11~18
|	UTF-8
|===

htmlファイルを読み込んでbeautifulsoupを使ってスクレイピングを行います。一例として
```
include::../generatecsv.py[]
```
のようにして表をcsvファイルに書き出した後dataframeとして取り出し、見出しとzipを使ってくっつけます。その過程は

download_and_scrape.ipynb

に記載してあり結果はgithubのdata以下に置いてあります。

- data/title_points.csv 作品投票結果(12回以降)
- data/char_points.csv キャラクター投票結果
- data/music_points.csv 楽曲投票結果

また総投票数にはかなりの変動があるため合計を1に正規化したデータも作成します。

- data/title_points_ratio.csv 正規化作品投票結果(12回以降)
- data/char_points_ratio.csv 正規化キャラクター投票結果
- data/music_points_ratio.csv 正規化楽曲投票結果
- data/music_points_ratio_sort.csv 登場順にソートされた正規化楽曲投票結果+作品、登場ステージ、登場年の一覧

これらの結果と東方Wiki http://thwiki.info 東方元ネタWiki 2nd https://seesaawiki.jp/toho-motoneta_2nd/ 
の楽曲、キャラの登場作品、面、自機に関する情報をcsv化したもの

- data/integertitles.csv 整数タイトル一覧
- data/nonintegertitles.csv 非整数タイトル一覧

- data/char_noninteger_list.csv 非整数タイトル登場キャラクター一覧
- data/mainchar_integer_list.csv 整数タイトル自機キャラクター一覧
- data/bosslist.csv 整数タイトルボスキャラクター一覧
- data/bookchar_list.csv 書籍のみ登場キャラクター一覧
- data/hifuu_list.csv 秘封倶楽部キャラクター一覧
- data/misc_chars.csv その他のキャラクター一覧

- data/music_noninteger_title.csv 非整数タイトル楽曲一覧

とを結合して、以下では考察、解析をしていきます。

== 記述統計

include::description.adoc[]

== ベイズ統計モデリング

include::bayes.adoc[]

== 参考書籍

include::reference.adoc[]

== あとがき

include::atogaki.adoc[]

<<<
include::okutsuke.adoc[]
